In [49]:
library(ggplot2)
library(microbiome)
library(phyloseq)
library("tidyverse")
library("dplyr")
library(vegan)
library(qiime2R)
library(microViz)
library(ComplexUpset)
set.seed(1)
library(SCRuB)

## Change fish species to standard names across databases

### Files run through worms to identify differences

In [2]:
# fish species to update from MIRe

## (python taxassign.py -i /Users/stephanie.rosales/Documents/omics_projects/MIR/metadata/speciesOfIntrest_1col.csv
#-a WoRMS -o /Users/stephanie.rosales/Documents/omics_projects/MIR/metadata/worms_SOI.cvs --n-proc 2)
tax_ref <- tibble::tribble(
  ~verbatimIdentification,              ~scientificName,
  "Acanthostracion polygonius",           "Acanthostracion polygonium",
  "Bairdiella sanctaeluciae",             "Corvula sanctaeluciae",
  "Chaetodon aculeatus",                 "Prognathodes aculeatus",
  "Chromis enchrysura",                  "Chromis enchrysurus",
  "Coryphopterus bol",                   "Coryphopterus venezuelae",
  "Enneanectes pectoralis",               "Enneanectes jordani",
  "Equetus lanceolatus",                 "Eques lanceolatus",
  "Eucinostomus lefroyi",                "Ulaema lefroyi",
  "Gobiosoma macrodon",                  "Tigrigobius macrodon",
  "Haemulon plumieri",                   "Haemulon plumierii",
  "Harengula humeralis",                 "Harengula jaguana",
  "Hemiemblemaria simulus",              "Hemiemblemaria simula",
  "Holocentrus coruscus",                "Sargocentron coruscum",
  "Hypoplectrus sp.",                    "Hypoplectrus",
  "Hypoplectrus Hybrid",                 "Hypoplectrus",
  "Labrisomus gobio",                    "Gobioclinus gobio",
  "Lipogramma trilineatum",              "Lipogramma trilineata",
  "Micrognathus ensenadae",              "Micrognathus crinitus",
  "Opistognathus whitehurstii",           "Opistognathus whitehursti",
  "Paradiplogrammus bairdi",              "Callionymus bairdi",
  "Ptereleotris calliurus",               "Ptereleotris calliura",
  "Sargocentron vexillarium",             "Neoniphon vexillarium",
  "Stephanolepis hispidus",               "Stephanolepis hispida",
  "Tigrigobius saucra",                   "Tigrigobius saucrus",
  "Trachinotus falcatus",                "Trachinotus blochii",
  "Chromis cyanea",                      "Azurina cyanea",
  "Chromis multilineata",                "Azurina multilineata",
  "Clepticus parrae",                    "Brama parrae",
  "Haemulon chrysargyreum",              "Brachygenys chrysargyrea"
)

##(python taxassign.py -i /Users/stephanie.rosales/Documents/omics_projects/MIR/metadata/NCRMP24_1col.csv 
#-a WoRMS -o /Users/stephanie.rosales/Documents/omics_projects/MIR/metadata/worms_ncrmp_fish24.cvs --n-proc 2)

worm_ncrmp= read.csv("/Users/stephanie.rosales/Documents/omics_projects/MIR/metadata/worms_ncrmp_fish24.csv",
              header = TRUE)

dim(worm_ncrmp)
dim(distinct(worm_ncrmp))
head(worm_ncrmp)

[1] 478  15

[1] 478  15

  verbatimIdentification    scientificName
1 Ablennes hians            Ablennes hians
2 Abudefduf saxatilis       Abudefduf saxatilis
3 Abudefduf taurus          Abudefduf taurus
4 Acanthemblemaria aspera   Acanthemblemaria aspera
5 Acanthemblemaria chaplini Acanthemblemaria chaplini
6 Acanthemblemaria maria    Acanthemblemaria maria
  scientificNameID                          taxonRank kingdom  phylum
1 urn:lsid:marinespecies.org:taxname:159246 Species   Animalia Chordata
2 urn:lsid:marinespecies.org:taxname:159288 Species   Animalia Chordata
3 urn:lsid:marinespecies.org:taxname:273701 Species   Animalia Chordata
4 urn:lsid:marinespecies.org:taxname:279443 Species   Animalia Chordata
5 urn:lsid:marinespecies.org:taxname:279448 Species   Animalia Chordata
6 urn:lsid:marinespecies.org:taxname:279457 Species   Animalia Chordata
  class     order                      family        genus            species
1 Teleostei Beloniformes               Belonidae     Ablennes         NA
2 Teleostei Ovalentaria incertae sedis Pomacentridae Abudefduf        NA
3 Teleostei Ovalentaria incertae sedis Pomacentridae Abudefduf        NA
4 Teleostei Blenniiformes              Chaenopsidae  Acanthemblemaria NA
5 Teleostei Blenniiformes              Chaenopsidae  Acanthemblemaria NA
6 Teleostei Blenniiformes              Chaenopsidae  Acanthemblemaria NA
  nameAccordingTo match_type_debug
1 WoRMS           Success_Batch_Ablennes hians
2 WoRMS           Success_Batch_Abudefduf saxatilis
3 WoRMS           Success_Batch_Abudefduf taurus
4 WoRMS           Success_Batch_Acanthemblemaria aspera
5 WoRMS           Success_Batch_Acanthemblemaria chaplini
6 WoRMS           Success_Batch_Acanthemblemaria maria
  cleanedTaxonomy           ambiguous
1 Ablennes hians            FALSE
2 Abudefduf saxatilis       FALSE
3 Abudefduf taurus          FALSE
4 Acanthemblemaria aspera   FALSE
5 Acanthemblemaria chaplini FALSE
6 Acanthemblemaria maria    FALSE

In [35]:
write.csv(density, "/Users/stephanie.rosales/Documents/omics_projects/MIR/Fish_comparison/Working_files/ncrmp_fish_24_denisty_worms.csv")

### Original files merged with worms output

In [80]:
# ----Species of Interest (SOI)----

# Read in the list of species of interest
soi_ori <- read.csv("/Users/stephanie.rosales/Documents/omics_projects/MIR/metadata/speciesOfIntrest.csv", header = TRUE)

head(soi_ori )

soi = soi_ori %>%

  # Join to the taxonomic reference table to standardize names
  # Match the SOI scientificName to the verbatimIdentification in tax_ref
  left_join(
    tax_ref,
    by = c("scientificName" = "verbatimIdentification")
  ) %>%
  
  # Preserve the original species name and replace it with the
  # updated/accepted scientific name when available
  mutate(
    scientificName_original = scientificName,
    scientificName = coalesce(scientificName.y, scientificName)
  ) %>%
  
  # Remove the extra joined column to clean up the table
  select(-scientificName.y)

# Inspect the resulting SOI table
head(soi)
dim(soi)

print("Identify species names that were updated via the taxonomic reference for SOI")
setdiff(soi$scientificName, soi$scientificName_original)

print("Count how many species names were changed")
length(setdiff(soi$scientificName, soi$scientificName_original))

write.csv(soi, "/Users/stephanie.rosales/Documents/omics_projects/MIR/Fish_comparison/Working_files/SOI_worm.csv")

# ---- NCRMP Density Data ----
# Read in NCRMP fish density data
remove_ncrmp=c("no observed fishes", "unknown species", "no observed fishes")

ncrmp_density <- read.table(
  "/Users/stephanie.rosales/Documents/omics_projects/MIR/metadata/ncrmp_fish_24_denisty.csv",
  header = TRUE,
  sep = "\t"
) 
head(ncrmp_density)

 density = ncrmp_density %>%
  
  # Flag records as originating from the NCRMP dataset
  mutate(NCRMP = "TRUE") %>%
  
  # Rename GROUP to Species for consistency across datasets
  rename(Species = GROUP) %>%
  
  # Retain only species identity and NCRMP presence
  #select(Species, NCRMP) %>%

  filter(!Species %in% remove_ncrmp) %>%
  # Join to the taxonomic reference table to standardize species names
  left_join(
    #tax_ref,
      worm_ncrmp, 
    by = c("Species" = "verbatimIdentification")
  ) %>%
  
  # Preserve the original species name and replace it with the standardized scientific name when available
  mutate(
    Species_original = Species,
    Species = coalesce(scientificName, Species)
  ) %>%
  
# Remove redundant taxonomic column 
  select(-scientificName)

# Inspect the resulting density table
head(density)
dim(density)

print("Identify species updated via the taxonomic reference")
setdiff(density$Species, density$Species_original)

print("Count how many species names were changed")
length(setdiff(density$Species, density$Species_original))

write.csv(density, "/Users/stephanie.rosales/Documents/omics_projects/MIR/Fish_comparison/Working_files/ncrmp_fish_24_denisty_worms.csv")

  Genus            Species   scientificName
1 Ablennes         hians     Ablennes hians
2 Abudefduf        saxatilis Abudefduf saxatilis
3 Abudefduf        taurus    Abudefduf taurus
4 Acanthemblemaria aspera    Acanthemblemaria aspera
5 Acanthemblemaria spinosa   Acanthemblemaria spinosa
6 Acanthemblemaria chaplini  Acanthemblemaria chaplini

  Genus            Species   scientificName
1 Ablennes         hians     Ablennes hians
2 Abudefduf        saxatilis Abudefduf saxatilis
3 Abudefduf        taurus    Abudefduf taurus
4 Acanthemblemaria aspera    Acanthemblemaria aspera
5 Acanthemblemaria spinosa   Acanthemblemaria spinosa
6 Acanthemblemaria chaplini  Acanthemblemaria chaplini
  scientificName_original
1 Ablennes hians
2 Abudefduf saxatilis
3 Abudefduf taurus
4 Acanthemblemaria aspera
5 Acanthemblemaria spinosa
6 Acanthemblemaria chaplini

[1] 373   4

[1] "Identify species names that were updated via the taxonomic reference for SOI"

 [1] "Acanthostracion polygonium" "Corvula sanctaeluciae"
 [3] "Prognathodes aculeatus"     "Azurina cyanea"
 [5] "Azurina multilineata"       "Chromis enchrysurus"
 [7] "Brama parrae"               "Coryphopterus venezuelae"
 [9] "Eques lanceolatus"          "Ulaema lefroyi"
[11] "Tigrigobius macrodon"       "Haemulon plumierii"
[13] "Brachygenys chrysargyrea"   "Hemiemblemaria simula"
[15] "Sargocentron coruscum"      "Hypoplectrus"
[17] "Gobioclinus gobio"          "Lipogramma trilineata"
[19] "Micrognathus crinitus"      "Opistognathus whitehursti"
[21] "Callionymus bairdi"         "Ptereleotris calliura"
[23] "Neoniphon vexillarium"      "Stephanolepis hispida"
[25] "Tigrigobius saucrus"        "Trachinotus blochii"

[1] "Count how many species names were changed"

[1] 26

  YEAR REGION   GROUP                  density    var n nm N     NM
1 2024 FLA KEYS Abudefduf saxatilis    0.94170542 0   1 NA 15126 213989.1
2 2024 FLA KEYS Acanthurus bahianus    0.28660600 0   1 NA 15126 213989.1
3 2024 FLA KEYS Acanthurus coeruleus   0.20471857 0   1 NA 15126 213989.1
4 2024 FLA KEYS Anisotremus virginicus 0.08188743 0   1 NA 15126 213989.1
5 2024 FLA KEYS Aulostomus maculatus   0.04094371 0   1 NA 15126 213989.1
6 2024 FLA KEYS Bodianus rufus         0.04094371 0   1 NA 15126 213989.1
  STAGE_LEVEL Reef
1 1           HS
2 1           HS
3 1           HS
4 1           HS
5 1           HS
6 1           HS

Warning message in left_join(., worm_ncrmp, by = c(Species = "verbatimIdentification")):
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 207 of `x` matches multiple rows in `y`.
ℹ Row 2 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.”

  YEAR REGION   Species                density    var n nm N     NM
1 2024 FLA KEYS Abudefduf saxatilis    0.94170542 0   1 NA 15126 213989.1
2 2024 FLA KEYS Acanthurus bahianus    0.28660600 0   1 NA 15126 213989.1
3 2024 FLA KEYS Acanthurus coeruleus   0.20471857 0   1 NA 15126 213989.1
4 2024 FLA KEYS Anisotremus virginicus 0.08188743 0   1 NA 15126 213989.1
5 2024 FLA KEYS Aulostomus maculatus   0.04094371 0   1 NA 15126 213989.1
6 2024 FLA KEYS Bodianus rufus         0.04094371 0   1 NA 15126 213989.1
  STAGE_LEVEL ⋯ class     order                      family        genus
1 1           ⋯ Teleostei Ovalentaria incertae sedis Pomacentridae Abudefduf
2 1           ⋯ Teleostei Acanthuriformes            Acanthuridae  Acanthurus
3 1           ⋯ Teleostei Acanthuriformes            Acanthuridae  Acanthurus
4 1           ⋯ Teleostei Eupercaria incertae sedis  Haemulidae    Anisotremus
5 1           ⋯ Teleostei Syngnathiformes            Aulostomidae  Aulostomus
6 1           ⋯ Teleostei Eupercaria incertae sedis  Labridae      Bodianus
  species nameAccordingTo match_type_debug
1 NA      WoRMS           Success_Batch_Abudefduf saxatilis
2 NA      WoRMS           Success_Batch_Acanthurus bahianus
3 NA      WoRMS           Success_Batch_Acanthurus coeruleus
4 NA      WoRMS           Success_Batch_Anisotremus virginicus
5 NA      WoRMS           Success_Batch_Aulostomus maculatus
6 NA      WoRMS           Success_Batch_Bodianus rufus
  cleanedTaxonomy        ambiguous Species_original
1 Abudefduf saxatilis    FALSE     Abudefduf saxatilis
2 Acanthurus bahianus    FALSE     Acanthurus bahianus
3 Acanthurus coeruleus   FALSE     Acanthurus coeruleus
4 Anisotremus virginicus FALSE     Anisotremus virginicus
5 Aulostomus maculatus   FALSE     Aulostomus maculatus
6 Bodianus rufus         FALSE     Bodianus rufus

[1] 212  26

[1] "Identify species updated via the taxonomic reference"

 [1] "Brachygenys chrysargyrea"   "Coryphopterus"
 [3] "Haemulon"                   "Acanthostracion polygonium"
 [5] "Caranx bartholomaei"        "Azurina cyanea"
 [7] "Azurina multilineata"       "Brama parrae"
 [9] "incertae sedis"             "Neoniphon vexillarium"
[11] "Trachinotus blochii"

[1] "Count how many species names were changed"

[1] 11

## Prepare data to remove sample contamination with SCRUB

In [53]:
#read metadata file and set factor order
meta_m3 = read.csv("/Users/stephanie.rosales/Documents/omics_projects/MIR/metadata//FAIRe-NOAA_noaa-aoml-mire - sampleMetadata.csv",
                skip = 2, header = TRUE, row.names=1) %>%
  filter(!is.na(libID_Marver3), libID_Marver3 != "")
head(meta_m3 , n=2)
dim(meta_m3 )

meta_m3  <- meta_m3[, colSums(is.na(meta_m3)) < nrow(meta_m3)]

rownames(meta_m3) <- meta_m3$libID_Marver3

head(meta_m3, n=2)
dim(meta_m3)

                                   samp_name_archive              month year
MIRe_10A_Horseshoe_CB-1_2024-05-23 MIR_eDNA1_24_144_c_HS_CB_1_10A May   2024
MIRe_10B_Horseshoe_CB-1_2024-05-23 MIR_eDNA1_24_144_c_HS_CB_1_10B May   2024
                                   date    serial_number extract_id
MIRe_10A_Horseshoe_CB-1_2024-05-23 5/23/24 HS_CB-1_10A   10A
MIRe_10B_Horseshoe_CB-1_2024-05-23 5/23/24 HS_CB-1_10B   10B
                                   sample_number libID_Marver1
MIRe_10A_Horseshoe_CB-1_2024-05-23 10            MIRe1_12S_MV1_10A
MIRe_10B_Horseshoe_CB-1_2024-05-23 10            MIRe1_12S_MV1_10B
                                   libID_Marver3     libID_Mifish     ⋯
MIRe_10A_Horseshoe_CB-1_2024-05-23 MIRe1_16S_MV3_10A MIRe1_12S_MF_10A ⋯
MIRe_10B_Horseshoe_CB-1_2024-05-23 MIRe1_16S_MV3_10B MIRe1_12S_MF_10B ⋯
                                   silicate_unit tot_alkalinity
MIRe_10A_Horseshoe_CB-1_2024-05-23 NA            NA
MIRe_10B_Horseshoe_CB-1_2024-05-23 NA            NA
                                   tot_alkalinity_unit transmittance
MIRe_10A_Horseshoe_CB-1_2024-05-23 NA                  NA
MIRe_10B_Horseshoe_CB-1_2024-05-23 NA                  NA
                                   transmittance_unit biosample_accession
MIRe_10A_Horseshoe_CB-1_2024-05-23 NA                 NA
MIRe_10B_Horseshoe_CB-1_2024-05-23 NA                 NA
                                   organism samp_collect_notes dna_yield
MIRe_10A_Horseshoe_CB-1_2024-05-23 seawater NA                 11.02
MIRe_10B_Horseshoe_CB-1_2024-05-23 seawater NA                 5.2
                                   dna_yield_unit
MIRe_10A_Horseshoe_CB-1_2024-05-23 ng
MIRe_10B_Horseshoe_CB-1_2024-05-23 ng

[1]  95 175

                  samp_name_archive              month year date
MIRe1_16S_MV3_10A MIR_eDNA1_24_144_c_HS_CB_1_10A May   2024 5/23/24
MIRe1_16S_MV3_10B MIR_eDNA1_24_144_c_HS_CB_1_10B May   2024 5/23/24
                  serial_number extract_id sample_number libID_Marver1
MIRe1_16S_MV3_10A HS_CB-1_10A   10A        10            MIRe1_12S_MV1_10A
MIRe1_16S_MV3_10B HS_CB-1_10B   10B        10            MIRe1_12S_MV1_10B
                  libID_Marver3     libID_Mifish     ⋯ filter_name
MIRe1_16S_MV3_10A MIRe1_16S_MV3_10A MIRe1_12S_MF_10A ⋯ Sterivex
MIRe1_16S_MV3_10B MIRe1_16S_MV3_10B MIRe1_12S_MF_10B ⋯ Sterivex
                  prepped_samp_store_sol samp_vol_we_dna_ext
MIRe1_16S_MV3_10A lysis buffer           2
MIRe1_16S_MV3_10B lysis buffer           2
                  samp_vol_we_dna_ext_unit tot_depth_water_col temp tidal_stage
MIRe1_16S_MV3_10A L                        10                  29.6 high
MIRe1_16S_MV3_10B L                        10                  29.6 high
                  organism dna_yield dna_yield_unit
MIRe1_16S_MV3_10A seawater 11.02     ng
MIRe1_16S_MV3_10B seawater 5.2       ng

[1] 95 64

In [54]:
#read metadata file and set factor order
meta_m1 = read.csv("/Users/stephanie.rosales/Documents/omics_projects/MIR/metadata//FAIRe-NOAA_noaa-aoml-mire - sampleMetadata.csv",
                skip = 2, header = TRUE, row.names=1) %>%
  filter(!is.na(libID_Marver1), libID_Marver1 != "")%>%   mutate(across(where(is.character), ~ str_replace_all(., "MIR-eDNA1", "2024:May"))) %>%
  mutate(across(where(is.character), ~ str_replace_all(., "MIR-eDNA2", "2024:Sept"))) %>%
  mutate(across(where(is.character), ~ str_replace_all(., "MIR-eDNA3", "2025:Feb")))

head(meta_m1, n=2)
dim(meta_m1)

meta_m1$libID_Marver1 <- gsub("MIRe1_12S_", "", meta_m1$libID_Marver1)
meta_m1$libID_Marver1 <- gsub("MIRe2_12S_", "", meta_m1$libID_Marver1)
meta_m1$libID_Marver1 <- gsub("MIRe3_12S_", "", meta_m1$libID_Marver1)

meta_m1$libID_Marver1 <- gsub("MV1_CFN_n_2A", "MV1_CFN", meta_m1$libID_Marver1)
meta_m1$libID_Marver1 <- gsub("MV1_CFS_n_2A", "MV1_CFS", meta_m1$libID_Marver1)
meta_m1$libID_Marver1 <- gsub("MV3_CR_n_3A", "MV3_CR", meta_m1$libID_Marver1)
meta_m1$libID_Marver3 <- gsub("MV3_HS_n_3A", "MV3_HS", meta_m1$libID_Marver1)
meta_m1 <- meta_m1[, colSums(is.na(meta_m1)) < nrow(meta_m1)]

rownames(meta_m1) <- meta_m1$libID_Marver1

head(meta_m1, n=2)
dim(meta_m1)

                                   samp_name_archive              month year
MIRe_10A_Horseshoe_CB-1_2024-05-23 MIR_eDNA1_24_144_c_HS_CB_1_10A May   2024
MIRe_10B_Horseshoe_CB-1_2024-05-23 MIR_eDNA1_24_144_c_HS_CB_1_10B May   2024
                                   date    serial_number extract_id
MIRe_10A_Horseshoe_CB-1_2024-05-23 5/23/24 HS_CB-1_10A   10A
MIRe_10B_Horseshoe_CB-1_2024-05-23 5/23/24 HS_CB-1_10B   10B
                                   sample_number libID_Marver1
MIRe_10A_Horseshoe_CB-1_2024-05-23 10            MIRe1_12S_MV1_10A
MIRe_10B_Horseshoe_CB-1_2024-05-23 10            MIRe1_12S_MV1_10B
                                   libID_Marver3     libID_Mifish     ⋯
MIRe_10A_Horseshoe_CB-1_2024-05-23 MIRe1_16S_MV3_10A MIRe1_12S_MF_10A ⋯
MIRe_10B_Horseshoe_CB-1_2024-05-23 MIRe1_16S_MV3_10B MIRe1_12S_MF_10B ⋯
                                   silicate_unit tot_alkalinity
MIRe_10A_Horseshoe_CB-1_2024-05-23 NA            NA
MIRe_10B_Horseshoe_CB-1_2024-05-23 NA            NA
                                   tot_alkalinity_unit transmittance
MIRe_10A_Horseshoe_CB-1_2024-05-23 NA                  NA
MIRe_10B_Horseshoe_CB-1_2024-05-23 NA                  NA
                                   transmittance_unit biosample_accession
MIRe_10A_Horseshoe_CB-1_2024-05-23 NA                 NA
MIRe_10B_Horseshoe_CB-1_2024-05-23 NA                 NA
                                   organism samp_collect_notes dna_yield
MIRe_10A_Horseshoe_CB-1_2024-05-23 seawater NA                 11.02
MIRe_10B_Horseshoe_CB-1_2024-05-23 seawater NA                 5.2
                                   dna_yield_unit
MIRe_10A_Horseshoe_CB-1_2024-05-23 ng
MIRe_10B_Horseshoe_CB-1_2024-05-23 ng

[1]  94 175

        samp_name_archive              month year date    serial_number
MV1_10A MIR_eDNA1_24_144_c_HS_CB_1_10A May   2024 5/23/24 HS_CB-1_10A
MV1_10B MIR_eDNA1_24_144_c_HS_CB_1_10B May   2024 5/23/24 HS_CB-1_10B
        extract_id sample_number libID_Marver1 libID_Marver3 libID_Mifish     ⋯
MV1_10A 10A        10            MV1_10A       MV1_10A       MIRe1_12S_MF_10A ⋯
MV1_10B 10B        10            MV1_10B       MV1_10B       MIRe1_12S_MF_10B ⋯
        filter_name prepped_samp_store_sol samp_vol_we_dna_ext
MV1_10A Sterivex    lysis buffer           2
MV1_10B Sterivex    lysis buffer           2
        samp_vol_we_dna_ext_unit tot_depth_water_col temp tidal_stage organism
MV1_10A L                        10                  29.6 high        seawater
MV1_10B L                        10                  29.6 high        seawater
        dna_yield dna_yield_unit
MV1_10A 11.02     ng
MV1_10B 5.2       ng

[1] 94 64

In [55]:
#read metadata file and set factor order
meta_mi = read.csv("/Users/stephanie.rosales/Documents/omics_projects/MIR/metadata//FAIRe-NOAA_noaa-aoml-mire - sampleMetadata.csv",
                skip = 2, header = TRUE, row.names=1) %>% 
  filter(!is.na(libID_Mifish), libID_Mifish != "") %>% 
  filter(libID_Mifish!="MIRe1_12S_MF_16B") %>% # remove no seqs
  filter(libID_Mifish!="MIRe2_12S_MF_33B") %>% # remove no seqs
  filter(libID_Mifish!="MIRe2_12S_MF_NTC") %>% # remove no seqs
mutate(across(where(is.character), ~ str_replace_all(., "MIR-eDNA1", "2024:May"))) %>%
  mutate(across(where(is.character), ~ str_replace_all(., "MIR-eDNA2", "2024:Sept"))) %>%
  mutate(across(where(is.character), ~ str_replace_all(., "MIR-eDNA3", "2025:Feb")))  %>%
  mutate(across(where(is.character), ~ str_replace_all(., "Checca_Rocks", "Checca Rocks")))

#meta <- meta[, colSums(is.na(meta)) < nrow(meta)]
rownames(meta_mi) <- meta_mi$libID_Mifish

head(meta_mi, n=2) 
dim(meta_mi)

                 samp_name_archive              month year date
MIRe1_12S_MF_10A MIR_eDNA1_24_144_c_HS_CB_1_10A May   2024 5/23/24
MIRe1_12S_MF_10B MIR_eDNA1_24_144_c_HS_CB_1_10B May   2024 5/23/24
                 serial_number extract_id sample_number libID_Marver1
MIRe1_12S_MF_10A HS_CB-1_10A   10A        10            MIRe1_12S_MV1_10A
MIRe1_12S_MF_10B HS_CB-1_10B   10B        10            MIRe1_12S_MV1_10B
                 libID_Marver3     libID_Mifish     ⋯ silicate_unit
MIRe1_12S_MF_10A MIRe1_16S_MV3_10A MIRe1_12S_MF_10A ⋯ NA
MIRe1_12S_MF_10B MIRe1_16S_MV3_10B MIRe1_12S_MF_10B ⋯ NA
                 tot_alkalinity tot_alkalinity_unit transmittance
MIRe1_12S_MF_10A NA             NA                  NA
MIRe1_12S_MF_10B NA             NA                  NA
                 transmittance_unit biosample_accession organism
MIRe1_12S_MF_10A NA                 NA                  seawater
MIRe1_12S_MF_10B NA                 NA                  seawater
                 samp_collect_notes dna_yield dna_yield_unit
MIRe1_12S_MF_10A NA                 11.02     ng
MIRe1_12S_MF_10B NA                 5.2       ng

[1] 161 175

In [56]:
#read ASV table

ASV_qza_3 <- read_qza("/Users/stephanie.rosales/Documents/omics_projects/MIR/analysis/seq_run2/marver3/qiime_output/table_Marver3_seq2.qza")
ASV_table_3 <- ASV_qza_3$data
head(ASV_table_3, n=2)
dim(ASV_table_3)

#read ASV table
ASV_qza_1 <- read_qza("/Users/stephanie.rosales/Documents/omics_projects/MIR/analysis/seq_run1//marver1/qiime_output//table_Marver1_seq1.qza")
ASV_table_1 <- ASV_qza_1$data
head(ASV_table_1, n=2)
dim(ASV_table_1)

#read ASV table
ASV_qza_mi <- read_qza("/Users/stephanie.rosales/Documents/omics_projects/MIR/analysis/seq_run1/mifish/qiime_output_sfl/table_Mifish_seq1_sfl.qza")
ASV_table_mi <- ASV_qza_mi$data
head(ASV_table_mi, n=2)
dim(ASV_table_mi)

Warning message in readLines(file, warn = readLines.warn):
“incomplete final line found on '/var/folders/j4/j37z3nw57wl5490t5t1rhk7h4k4czw/T//RtmpegPLI4/f3a13815-e359-48a3-bd84-a8fb292f7c66/metadata.yaml'”

                                 MIRe1_16S_MV3_10A MIRe1_16S_MV3_10B
24603dde52fe88f5148c3c60c5d6e1b2 79820             5257
ece06f5929d636c6850f5444574486f5     0                0
                                 MIRe1_16S_MV3_11A MIRe1_16S_MV3_11B
24603dde52fe88f5148c3c60c5d6e1b2 4819              14456
ece06f5929d636c6850f5444574486f5 3692                922
                                 MIRe1_16S_MV3_12A MIRe1_16S_MV3_12B
24603dde52fe88f5148c3c60c5d6e1b2 78936             499167
ece06f5929d636c6850f5444574486f5 15980                578
                                 MIRe1_16S_MV3_13A MIRe1_16S_MV3_13B
24603dde52fe88f5148c3c60c5d6e1b2 177978            111711
ece06f5929d636c6850f5444574486f5   3359             16764
                                 MIRe1_16S_MV3_14A MIRe1_16S_MV3_14B ⋯
24603dde52fe88f5148c3c60c5d6e1b2 58426             309238            ⋯
ece06f5929d636c6850f5444574486f5 27704              47524            ⋯
                                 MIRe2_16S_MV3_47B MIRe2_16S_MV3_48A
24603dde52fe88f5148c3c60c5d6e1b2 52481             46816
ece06f5929d636c6850f5444574486f5    15                 6
                                 MIRe2_16S_MV3_48B MIRe2_16S_MV3_CFN
24603dde52fe88f5148c3c60c5d6e1b2 115286            347039
ece06f5929d636c6850f5444574486f5  10508                 0
                                 MIRe2_16S_MV3_CFS MIRe2_16S_MV3_CR
24603dde52fe88f5148c3c60c5d6e1b2 0                 14894
ece06f5929d636c6850f5444574486f5 0                    14
                                 MIRe2_16S_MV3_ExBlank MIRe2_16S_MV3_HS
24603dde52fe88f5148c3c60c5d6e1b2 141                   10143
ece06f5929d636c6850f5444574486f5   0                       0
                                 MIRe2_16S_MV3_MSU MIRe2_16S_MV3_NTC
24603dde52fe88f5148c3c60c5d6e1b2 0                 0
ece06f5929d636c6850f5444574486f5 0                 0

[1] 3646   96

Warning message in readLines(file, warn = readLines.warn):
“incomplete final line found on '/var/folders/j4/j37z3nw57wl5490t5t1rhk7h4k4czw/T//RtmpegPLI4/0a1e94ca-571d-445c-aa1c-e95417698541/metadata.yaml'”

                                 MV1_10A MV1_10B MV1_11A MV1_11B MV1_12A
e03b6ee0df42c3ca44ea26ed6c4d27aa 105     38519   16102   36958   54713
7da05e198a2c205b708d4f3ebeb5ee12   0      9978       0   27847   18627
                                 MV1_12B MV1_13A MV1_13B MV1_14A MV1_14B ⋯
e03b6ee0df42c3ca44ea26ed6c4d27aa 272060  215056  49484   70268   103651  ⋯
7da05e198a2c205b708d4f3ebeb5ee12   1068   44412  25778   36252    83416  ⋯
                                 MV1_9B MV1_CFN MV1_CFS MV1_CR MV1_ExBlank
e03b6ee0df42c3ca44ea26ed6c4d27aa 37515  9776    137621  87712      0
7da05e198a2c205b708d4f3ebeb5ee12  7870  1231         0      0  45127
                                 MV1_HS MV1_MSU MV1_neg1A MV1_neg1B MV1_NTC
e03b6ee0df42c3ca44ea26ed6c4d27aa 255833 100942  213134    356518    6
7da05e198a2c205b708d4f3ebeb5ee12   3118      0       0         0    0

[1] 2685   96

Warning message in readLines(file, warn = readLines.warn):
“incomplete final line found on '/var/folders/j4/j37z3nw57wl5490t5t1rhk7h4k4czw/T//RtmpegPLI4/5150b7d2-9611-43a5-8a7e-a3d8e8449c01/metadata.yaml'”

                                 MIRe1_12S_MF_10A MIRe1_12S_MF_10B
5e704746baef0d3e632a7def74b449b9     0            42501
addd57bd3b3937b61b32dece26f8f166 25957                0
                                 MIRe1_12S_MF_11A MIRe1_12S_MF_11B
5e704746baef0d3e632a7def74b449b9 0                    0
addd57bd3b3937b61b32dece26f8f166 0                31805
                                 MIRe1_12S_MF_12A MIRe1_12S_MF_12B
5e704746baef0d3e632a7def74b449b9    11            4
addd57bd3b3937b61b32dece26f8f166 16427            3
                                 MIRe1_12S_MF_13A MIRe1_12S_MF_13B
5e704746baef0d3e632a7def74b449b9 14376             7424
addd57bd3b3937b61b32dece26f8f166 30234            33756
                                 MIRe1_12S_MF_14A MIRe1_12S_MF_14B ⋯
5e704746baef0d3e632a7def74b449b9  8864                 0           ⋯
addd57bd3b3937b61b32dece26f8f166 41302            178084           ⋯
                                 MIRe3_12S_MF_72A MIRe3_12S_MF_72B
5e704746baef0d3e632a7def74b449b9  9871                0
addd57bd3b3937b61b32dece26f8f166 95071            44794
                                 MIRe3_12S_MF_CFN_n_3A MIRe3_12S_MF_CFS_n_3A
5e704746baef0d3e632a7def74b449b9 0                     0
addd57bd3b3937b61b32dece26f8f166 0                     0
                                 MIRe3_12S_MF_CR_n_3A MIRe3_12S_MF_CR_n_3B
5e704746baef0d3e632a7def74b449b9 503586               0
addd57bd3b3937b61b32dece26f8f166      0               0
                                 MIRe3_12S_MF_ExBlank MIRe3_12S_MF_HS_n_3A
5e704746baef0d3e632a7def74b449b9 0                    0
addd57bd3b3937b61b32dece26f8f166 0                    0
                                 MIRe3_12S_MF_NTC MIRe3_12S_MF_NTC2
5e704746baef0d3e632a7def74b449b9 0                0
addd57bd3b3937b61b32dece26f8f166 0                0

[1] 5729  165

In [57]:
taxa_qza <- read_qza("/Users/stephanie.rosales/Documents/omics_projects//MIR//analysis/seq_run2//marver3/qiime_output//taxonomy_marver3_seq2.qza")
taxa_table_3 <- taxa_qza$data %>%
as_tibble() %>% 
#filter(Taxon!="Unassigned") %>%
#select(-Consensus) %>% 
separate(Taxon, sep=";", c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")) %>%
arrange(Feature.ID) %>%
mutate(ASVs =paste('ASV',1:n(), sep = "_")) %>%
#mutate(Genus = sub("g__", "", Genus)) %>%
#mutate(Genus = sub("_[0-9]+", "", Genus)) %>%
column_to_rownames("Feature.ID")%>%
#filter(Domain!="Unassigned") %>%
as.matrix()

head(taxa_table_3)


taxa_qza <- read_qza("/Users/stephanie.rosales/Documents/omics_projects//MIR//analysis//seq_run1//marver1/qiime_output//taxa_Marver1_seq1.qza")
taxa_table_1 <- taxa_qza$data %>%
as_tibble() %>% 
#filter(Taxon!="Unassigned") %>%
#select(-Consensus) %>% 
separate(Taxon, sep=";", c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")) %>%
arrange(Feature.ID) %>%
mutate(ASVs =paste('ASV',1:n(), sep = "_")) %>%
mutate(Genus = sub("g__", "", Genus)) %>%
mutate(Genus = sub("_[0-9]+", "", Genus)) %>%
mutate(Species = sub("s__", "", Species)) %>%
mutate(Species = sub("_[0-9]+", "", Species)) %>%
mutate(Family = sub("c__", "", Family)) %>%
mutate(Family = sub("_[0-9]+", "", Family)) %>%
mutate(Family = sub("c__", "", Class)) %>%
mutate(Family = sub("_[0-9]+", "", Class)) %>%
column_to_rownames("Feature.ID")%>%
#filter(Domain!="Unassigned") %>%
as.matrix()

head(taxa_table_1)
dim(taxa_table_1)


taxa_qza <- read_qza("/Users/stephanie.rosales/Documents/omics_projects/MIR/analysis/seq_run1/mifish/qiime_output_sfl_mislabelled_db/taxa_Mifish_seq1_sfl.qza")
taxa_table_mi <- taxa_qza$data %>%
as_tibble() %>% 
#filter(Taxon!="Unassigned") %>%
#select(-Consensus) %>% 
separate(Taxon, sep=";", c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")) %>%
arrange(Feature.ID) %>%
mutate(ASVs =paste('ASV',1:n(), sep = "_")) %>%
column_to_rownames("Feature.ID")%>%
#filter(Domain!="Unassigned") %>%
as.matrix()

head(taxa_table_mi)

Warning message in readLines(file, warn = readLines.warn):
“incomplete final line found on '/var/folders/j4/j37z3nw57wl5490t5t1rhk7h4k4czw/T//RtmpegPLI4/b3310273-c770-404d-8408-fb19d766a6c0/metadata.yaml'”
Warning message:
“Expected 7 pieces. Missing pieces filled with `NA` in 2181 rows [1, 2, 3, 4, 6, 8, 9, 10, 11, 13, 14, 16, 17, 19, 20, 21, 22, 23, 26, 27, ...].”

                                 Domain     Phylum   Class       Order
0003b70454d6e57dfd7fda9b667caeef NA         Chordata Actinopteri NA
0013ed0613e0d3a0fd82aac84c315107 NA         Chordata Actinopteri Labriformes
0014f6c3f5307e0d8e1b5451649628b8 NA         Chordata Actinopteri NA
001ca7ce36a6a1a8062af013da7effb3 NA         Chordata Actinopteri Blenniiformes
0027bd427ee4d866a7f601fb755a153b NA         Chordata Mammalia    Primates
002ef3036f081b912ae9adf224485d6b Unassigned NA       NA          NA
                                 Family         Genus Species      Consensus
0003b70454d6e57dfd7fda9b667caeef NA             NA    NA           1
0013ed0613e0d3a0fd82aac84c315107 Labridae       NA    NA           1
0014f6c3f5307e0d8e1b5451649628b8 NA             NA    NA           1
001ca7ce36a6a1a8062af013da7effb3 Tripterygiidae NA    NA           1
0027bd427ee4d866a7f601fb755a153b Hominidae      Homo  Homo sapiens 1
002ef3036f081b912ae9adf224485d6b NA             NA    NA           1
                                 ASVs
0003b70454d6e57dfd7fda9b667caeef ASV_1
0013ed0613e0d3a0fd82aac84c315107 ASV_2
0014f6c3f5307e0d8e1b5451649628b8 ASV_3
001ca7ce36a6a1a8062af013da7effb3 ASV_4
0027bd427ee4d866a7f601fb755a153b ASV_5
002ef3036f081b912ae9adf224485d6b ASV_6

Warning message in readLines(file, warn = readLines.warn):
“incomplete final line found on '/var/folders/j4/j37z3nw57wl5490t5t1rhk7h4k4czw/T//RtmpegPLI4/147c8941-1e23-4ac1-b4c3-c12391fc0133/metadata.yaml'”
Warning message:
“Expected 7 pieces. Missing pieces filled with `NA` in 601 rows [5, 7, 16, 20, 30, 34, 40, 51, 52, 57, 67, 69, 72, 76, 86, 92, 93, 102, 105, 111, ...].”

                                 Domain            Phylum
000f0d9e1c3064a70badeae45f2ba9df k__Eukaryota_2759 p__Chordata_7711
002f0c450b3b355ca242b514b52193b6 k__Eukaryota_2759 p__Chordata_7711
003e93968a2d5718f84db64839cb6f78 k__Eukaryota_2759 p__Chordata_7711
005e51ef90d4797ccf1568b01178f647 k__Eukaryota_2759 p__Chordata_7711
0070c281ab8ed641c2224cabbf034212 k__Eukaryota_2759 NA
0080f3931a7d1e297e3131d8d5608f36 k__Eukaryota_2759 p__Chordata_7711
                                 Class
000f0d9e1c3064a70badeae45f2ba9df c__Actinopteri_186623
002f0c450b3b355ca242b514b52193b6 c__Actinopteri_186623
003e93968a2d5718f84db64839cb6f78 c__Chondrichthyes_7777
005e51ef90d4797ccf1568b01178f647 c__Actinopteri_186623
0070c281ab8ed641c2224cabbf034212 NA
0080f3931a7d1e297e3131d8d5608f36 c__Actinopteri_186623
                                 Order                        Family
000f0d9e1c3064a70badeae45f2ba9df o__Chaetodontiformes_1545895 c__Actinopteri
002f0c450b3b355ca242b514b52193b6 o__Lutjaniformes_2024539     c__Actinopteri
003e93968a2d5718f84db64839cb6f78 o__Myliobatiformes_117851    c__Chondrichthyes
005e51ef90d4797ccf1568b01178f647 o__Clupeiformes_32446        c__Actinopteri
0070c281ab8ed641c2224cabbf034212 NA                           NA
0080f3931a7d1e297e3131d8d5608f36 o__Centrarchiformes_1489940  c__Actinopteri
                                 Genus       Species
000f0d9e1c3064a70badeae45f2ba9df Chaetodon   Chaetodon ocellatus
002f0c450b3b355ca242b514b52193b6 Anisotremus Anisotremus surinamensis
003e93968a2d5718f84db64839cb6f78 Aetobatus   Aetobatus narinari
005e51ef90d4797ccf1568b01178f647 Opisthonema Opisthonema oglinum
0070c281ab8ed641c2224cabbf034212 NA          NA
0080f3931a7d1e297e3131d8d5608f36 Kyphosus    NA
                                 Confidence ASVs
000f0d9e1c3064a70badeae45f2ba9df 1.0000000  ASV_1
002f0c450b3b355ca242b514b52193b6 0.9997477  ASV_2
003e93968a2d5718f84db64839cb6f78 1.0000000  ASV_3
005e51ef90d4797ccf1568b01178f647 1.0000000  ASV_4
0070c281ab8ed641c2224cabbf034212 1.0000000  ASV_5
0080f3931a7d1e297e3131d8d5608f36 0.9999999  ASV_6

[1] 2685    9

Warning message in readLines(file, warn = readLines.warn):
“incomplete final line found on '/var/folders/j4/j37z3nw57wl5490t5t1rhk7h4k4czw/T//RtmpegPLI4/b5221f12-6970-4f41-b841-e1cb15925c71/metadata.yaml'”
Warning message:
“Expected 7 pieces. Missing pieces filled with `NA` in 1285 rows [1, 5, 23, 24, 33, 42, 43, 45, 48, 49, 50, 54, 62, 63, 69, 75, 87, 89, 95, 109, ...].”

                                 Domain    Phylum   Class       Order
0019b435c1e20c18dedcc08182c39813 Eukaryota Chordata Actinopteri NA
00238158fdd2d6aa0a4d1c493277ac00 Eukaryota Chordata Actinopteri NA
00260f732981b4453ef2e5777bdb8d08 Eukaryota Chordata Actinopteri Labriformes
002697bf26f2728dfdf10de8059bf039 Eukaryota Chordata Actinopteri NA
003c0983d1daf45eedde902221cb8539 Eukaryota Chordata Actinopteri NA
0042ee14d9c27c8afe636c66aeb95d86 Eukaryota Chordata Actinopteri Labriformes
                                 Family        Genus     Species
0019b435c1e20c18dedcc08182c39813 Haemulidae    Haemulon  Haemulon macrostomum
00238158fdd2d6aa0a4d1c493277ac00 Pomacentridae Stegastes Stegastes diencaeus
00260f732981b4453ef2e5777bdb8d08 Labridae      Scarus    Scarus coeruleus
002697bf26f2728dfdf10de8059bf039 NA            NA        NA
003c0983d1daf45eedde902221cb8539 NA            NA        NA
0042ee14d9c27c8afe636c66aeb95d86 Labridae      Sparisoma Sparisoma radians
                                 Confidence ASVs
0019b435c1e20c18dedcc08182c39813 0.9856335  ASV_1
00238158fdd2d6aa0a4d1c493277ac00 1.0000000  ASV_2
00260f732981b4453ef2e5777bdb8d08 1.0000000  ASV_3
002697bf26f2728dfdf10de8059bf039 0.9998789  ASV_4
003c0983d1daf45eedde902221cb8539 0.8885351  ASV_5
0042ee14d9c27c8afe636c66aeb95d86 0.9995541  ASV_6

In [58]:
ASV_table_mi_df= as.data.frame(ASV_table_mi)
ASV_table_mi_df <- ASV_table_mi_df[, colSums(ASV_table_mi_df) > 0]

In [59]:

# remove differences in sampleID and sequence ID for MARVER1
setdiff(colnames(ASV_table_1),rownames(meta_m1))
ASV_table_1_df= as.data.frame(ASV_table_1) %>%
select(-MV1_CR, -MV1_HS, -MV1_MSU, -MV1_NTC) 

setdiff(colnames(ASV_table_1_df),rownames(meta_m1))
length(setdiff(colnames(ASV_table_1_df),rownames(meta_m1)))


# remove differences in sampleID and sequence ID for MARVER3
setdiff(colnames(ASV_table_3),rownames(meta_m3))


ASV_table_3_df= as.data.frame(ASV_table_3) %>%
select(-MIRe2_16S_MV3_MSU, -MIRe2_16S_MV3_NTC) 
setdiff(colnames(ASV_table_3_df),rownames(meta_m3))
length(setdiff(colnames(ASV_table_3_df),rownames(meta_m3)))



# remove differences in sampleID and sequence ID for Mifish
setdiff(colnames(ASV_table_mi),rownames(meta_mi))


ASV_table_mi_df= as.data.frame(ASV_table_mi) %>%
select(-MIRe1_12S_MF_16B, -MIRe2_12S_MF_33B, -MIRe2_12S_MF_CR_n_2B, -MIRe3_12S_MF_NTC) 
setdiff(colnames(ASV_table_mi_df),rownames(meta_mi))
length(setdiff(colnames(ASV_table_mi_df),rownames(meta_mi)))

[1] "MV1_CR"  "MV1_HS"  "MV1_MSU" "MV1_NTC"

character(0)

[1] 0

[1] "MIRe2_16S_MV3_MSU" "MIRe2_16S_MV3_NTC"

character(0)

[1] 0

[1] "MIRe1_12S_MF_16B"     "MIRe2_12S_MF_33B"     "MIRe2_12S_MF_CR_n_2B"
[4] "MIRe3_12S_MF_NTC"

character(0)

[1] 0

In [60]:
setdiff(row.names(meta_mi),colnames(ASV_table_mi_df))
length(setdiff(colnames(ASV_table_mi_df),rownames(meta_mi)))

character(0)

[1] 0

### Prepare metadata for SCRUB

In [61]:
scrub_meta_3 <- 
 #data.frame(sample_data(ps_3))  %>% as.data.frame() %>%
meta_m3 %>%
  transmute(
    is_control   = samp_category != "sample",
    sample_type  = samp_category,
    #sample_well  = extract_number
    #sample_type  = neg_cont_type
  ) %>%
  as.data.frame()

# Preserve original rownames from meta
rownames(scrub_meta_3) <- rownames(meta_m3)

# Quick QC
scrub_meta_3 %>% count(is_control, sample_type)
head(scrub_meta_3)
dim(scrub_meta_3)

# Reorder metadata to match ASV table
scrub_meta_3 <- scrub_meta_3[rownames(t(ASV_table_3_df)), ]

  is_control sample_type      n
1 FALSE      sample           87
2  TRUE      negative control  8

                  is_control sample_type
MIRe1_16S_MV3_10A FALSE      sample
MIRe1_16S_MV3_10B FALSE      sample
MIRe1_16S_MV3_11A FALSE      sample
MIRe1_16S_MV3_11B FALSE      sample
MIRe1_16S_MV3_12A FALSE      sample
MIRe1_16S_MV3_12B FALSE      sample

[1] 95  2

In [62]:
scrub_meta_1 <- 
 #data.frame(sample_data(ps_3))  %>% as.data.frame() %>%
meta_m1 %>%
  transmute(
    is_control   = samp_category != "sample",
    sample_type  = samp_category,
    #sample_well  = extract_number,
    #sample_type  = neg_cont_type
  ) %>%
  as.data.frame()

# Preserve original rownames from meta
rownames(scrub_meta_1) <- rownames(meta_m1)

# Quick QC
scrub_meta_1 %>% count(is_control, sample_type)
head(scrub_meta_1)
dim(scrub_meta_1)

# Reorder metadata to match ASV table
scrub_meta_1 <- scrub_meta_1[rownames(t(ASV_table_1_df)), ]

  is_control sample_type      n
1 FALSE      sample           87
2  TRUE      negative control  7

        is_control sample_type
MV1_10A FALSE      sample
MV1_10B FALSE      sample
MV1_11A FALSE      sample
MV1_11B FALSE      sample
MV1_12A FALSE      sample
MV1_12B FALSE      sample

[1] 94  2

In [63]:
scrub_meta_mi <- 
 #data.frame(sample_data(ps_3))  %>% as.data.frame() %>%
meta_mi %>%
  transmute(
    is_control   = samp_category != "sample",
    sample_type  = samp_category,
    #sample_well  = extract_number,
    #   sample_type  = neg_cont_type
  ) %>%
  as.data.frame()

# Preserve original rownames from meta
rownames(scrub_meta_mi) <- rownames(meta_mi)

# Quick QC
scrub_meta_mi %>% count(is_control, sample_type)
head(scrub_meta_mi)
dim(scrub_meta_mi)

# Reorder metadata to match ASV table
scrub_meta_mi <- scrub_meta_mi[rownames(t(ASV_table_mi_df)), ]

  is_control sample_type      n
1 FALSE      sample           142
2  TRUE      negative control  19

                 is_control sample_type
MIRe1_12S_MF_10A FALSE      sample
MIRe1_12S_MF_10B FALSE      sample
MIRe1_12S_MF_11A FALSE      sample
MIRe1_12S_MF_11B FALSE      sample
MIRe1_12S_MF_12A FALSE      sample
MIRe1_12S_MF_12B FALSE      sample

[1] 161   2

### Prepare SCRUB sequence count table

In [64]:
ps_3 = phyloseq(otu_table(ASV_table_3_df, taxa_are_rows=TRUE), 
               sample_data(meta_m3),
tax_table(taxa_table_3))
ps_3  

ps_1 = phyloseq(otu_table(ASV_table_1_df, taxa_are_rows=TRUE), 
               sample_data(meta_m1),
tax_table(taxa_table_1))
ps_1 %>% tax_fix()


ps_mi = phyloseq(otu_table(ASV_table_mi_df, taxa_are_rows=TRUE), 
               sample_data(meta_mi),
tax_table(taxa_table_mi))
ps_mi %>% tax_fix()

ps_mi <- prune_samples(sample_sums(ps_mi) > 0, ps_mi)
ps_mi

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3646 taxa and 94 samples ]
sample_data() Sample Data:       [ 94 samples by 64 sample variables ]
tax_table()   Taxonomy Table:    [ 3646 taxa by 9 taxonomic ranks ]

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2685 taxa and 92 samples ]
sample_data() Sample Data:       [ 92 samples by 64 sample variables ]
tax_table()   Taxonomy Table:    [ 2685 taxa by 9 taxonomic ranks ]

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 4712 taxa and 161 samples ]
sample_data() Sample Data:       [ 161 samples by 175 sample variables ]
tax_table()   Taxonomy Table:    [ 4712 taxa by 9 taxonomic ranks ]

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 4712 taxa and 159 samples ]
sample_data() Sample Data:       [ 159 samples by 175 sample variables ]
tax_table()   Taxonomy Table:    [ 4712 taxa by 9 taxonomic ranks ]

In [65]:
otu_df_3 <- as.data.frame(t(otu_table(ps_3)))
otu_df_1 <- as.data.frame(t(otu_table(ps_1)))
otu_df_mi <- as(otu_table(t(ps_mi)), "matrix")

In [72]:
dim(otu_df_mi)
dim(scrub_meta_mi)

dim(otu_df_3)
dim(scrub_meta_3)

[1]  159 4712

[1] 159   2

[1]   94 3646

[1] 94  2

In [70]:
setdiff(rownames(scrub_meta_mi),rownames(otu_df_mi))
length(setdiff(colnames(scrub_meta_mi),rownames(otu_df_mi)))

setdiff(row.names(otu_df_mi),row.names(scrub_meta_mi))
length(setdiff(row.names(otu_df_mi),row.names(scrub_meta_mi)))

[1] "MIRe2_12S_MF_CFS_n_2A"     "MIRe2_12S_MF_ExBlank_p2ws"

[1] 2

character(0)

[1] 0

In [71]:
rows_to_remove <- c("MIRe2_12S_MF_CFS_n_2A", "MIRe2_12S_MF_ExBlank_p2ws")
scrub_meta_mi <- scrub_meta_mi[!rownames(scrub_meta_mi) %in% rows_to_remove, ]
setdiff(rownames(scrub_meta_mi),rownames(otu_df_mi))
length(setdiff(colnames(scrub_meta_mi),rownames(otu_df_mi)))

character(0)

[1] 2

### Run SCRUB

In [73]:
scr_out_3 <- SCRuB(otu_df_3,
                 scrub_meta_3,
                   #control_order =  c('field negative', 'extraction negative')
                  )

[1] "Did not find well metadata, running SCRuB without the spatial component"
[1] "SCRuBbing away contamination in the negative control controls..."

In [74]:
scr_out_1 <- SCRuB(otu_df_1,
                 scrub_meta_1,
                   #control_order =  c('field negative', 'extraction negative')
                  )

[1] "Did not find well metadata, running SCRuB without the spatial component"
[1] "SCRuBbing away contamination in the negative control controls..."

In [75]:
scr_out_mi <- SCRuB(otu_df_mi,
                 scrub_meta_mi, 
                   #control_order =  c('field negative', 'extraction negative')
                  )

[1] "Did not find well metadata, running SCRuB without the spatial component"
[1] "SCRuBbing away contamination in the negative control controls..."

In [76]:
decontaminated_m3 <- as.data.frame(scr_out_3$decontaminated_samples)
head(decontaminated_m3, n=2)
dim(decontaminated_m3)

decontaminated_m1 <- as.data.frame(scr_out_1$decontaminated_samples)
head(decontaminated_m1, n=2)
dim(decontaminated_m1)


decontaminated_mi <- as.data.frame(scr_out_mi$decontaminated_samples)
head(decontaminated_mi, n=2)
dim(decontaminated_mi)

                  24603dde52fe88f5148c3c60c5d6e1b2
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  ece06f5929d636c6850f5444574486f5
MIRe1_16S_MV3_10A     0
MIRe1_16S_MV3_10B     0
MIRe1_16S_MV3_11A  3688
MIRe1_16S_MV3_11B     0
MIRe1_16S_MV3_12A 15911
MIRe1_16S_MV3_12B     0
                  52101314bc187461c2d4c5b5dabe6a89
MIRe1_16S_MV3_10A     0
MIRe1_16S_MV3_10B     0
MIRe1_16S_MV3_11A     0
MIRe1_16S_MV3_11B     0
MIRe1_16S_MV3_12A 54595
MIRe1_16S_MV3_12B     0
                  33534b6a6f23bd8acb02bf8490fd822f
MIRe1_16S_MV3_10A     0
MIRe1_16S_MV3_10B  6988
MIRe1_16S_MV3_11A     0
MIRe1_16S_MV3_11B 12758
MIRe1_16S_MV3_12A  8186
MIRe1_16S_MV3_12B     0
                  07b1d9f7e7dce81c3b240e3e3f5f997b
MIRe1_16S_MV3_10A  8247
MIRe1_16S_MV3_10B  8273
MIRe1_16S_MV3_11A     0
MIRe1_16S_MV3_11B  2272
MIRe1_16S_MV3_12A 25363
MIRe1_16S_MV3_12B     0
                  a23cbfdeaeb29f2bbeefad65c4c4b2f8
MIRe1_16S_MV3_10A    27
MIRe1_16S_MV3_10B 11450
MIRe1_16S_MV3_11A   351
MIRe1_16S_MV3_11B     0
MIRe1_16S_MV3_12A     0
MIRe1_16S_MV3_12B     0
                  cfd8220f906a1a19cbc73ef31b76021a
MIRe1_16S_MV3_10A     0
MIRe1_16S_MV3_10B   211
MIRe1_16S_MV3_11A     0
MIRe1_16S_MV3_11B 16928
MIRe1_16S_MV3_12A  2282
MIRe1_16S_MV3_12B   138
                  d4878bc3fe3c131cc7ecbf55edfb7425
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  88f1a1d09d11fe06660d80c1ba4d0602
MIRe1_16S_MV3_10A 39894
MIRe1_16S_MV3_10B 15000
MIRe1_16S_MV3_11A  2431
MIRe1_16S_MV3_11B     0
MIRe1_16S_MV3_12A     0
MIRe1_16S_MV3_12B     0
                  bb3462b2d489dce1d47ac04d740ee4b0 ⋯
MIRe1_16S_MV3_10A 28104                            ⋯
MIRe1_16S_MV3_10B   112                            ⋯
MIRe1_16S_MV3_11A   932                            ⋯
MIRe1_16S_MV3_11B 64523                            ⋯
MIRe1_16S_MV3_12A 12877                            ⋯
MIRe1_16S_MV3_12B   449                            ⋯
                  25377f38430f0105aa6864ab9fcc91f0
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  3e62d96191146acaa8f2d2b78ce1b517
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  3994488d4d6cbc2f6404f133da00fc1a
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  749e8768124864616f3365f02dce7989
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  204420ca4c8d6408a9b4b9cbf9b2b594
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  991e059c0c201fac5d606103618d1420
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  33bf4041a5f273a89407b355992ff65a
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  f4289d9ffb552441dd6742d731a328a9
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  6a2d26dc3c5a733b337d15ca60d246a7
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0
                  f157408f0b2f33dc25486a3dd7a08464
MIRe1_16S_MV3_10A 0
MIRe1_16S_MV3_10B 0
MIRe1_16S_MV3_11A 0
MIRe1_16S_MV3_11B 0
MIRe1_16S_MV3_12A 0
MIRe1_16S_MV3_12B 0

[1]   87 3646

        e03b6ee0df42c3ca44ea26ed6c4d27aa 7da05e198a2c205b708d4f3ebeb5ee12
MV1_10A 0                                0
MV1_10B 0                                0
MV1_11A 0                                0
MV1_11B 0                                0
MV1_12A 0                                0
MV1_12B 0                                0
        83c356d0ebc3a8e44e76aab2fa442c6d ef4d7a661ddc4fbcce5cef9569d8c574
MV1_10A 0                                   93
MV1_10B 0                                64238
MV1_11A 0                                    0
MV1_11B 0                                    0
MV1_12A 0                                    0
MV1_12B 0                                    0
        c88db9b123be52c2969a0aaf38ee3128 68fbbdf8bd741af2251a9a1c5f4a5162
MV1_10A 0                                   0
MV1_10B 0                                   0
MV1_11A 0                                   0
MV1_11B 0                                4955
MV1_12A 0                                   0
MV1_12B 0                                 235
        23a65576114e6d5cffd94635c5bb6e60 9978fc802c7bf691234eef89494b0ec4
MV1_10A     0                            0
MV1_10B  4663                            0
MV1_11A  6859                            0
MV1_11B 19052                            0
MV1_12A 59977                            0
MV1_12B     0                            0
        7849d39c640cecb0070c4aa6eb65657c 59397773cc737943383d87a7db391c6a ⋯
MV1_10A 0                                0                                ⋯
MV1_10B 0                                0                                ⋯
MV1_11A 0                                0                                ⋯
MV1_11B 0                                0                                ⋯
MV1_12A 0                                0                                ⋯
MV1_12B 0                                0                                ⋯
        6f9712e56079f0d6002b2c1d053ef609 3218aaa7642b62a54e96fe488cd8f4d4
MV1_10A 0                                0
MV1_10B 0                                0
MV1_11A 0                                0
MV1_11B 0                                0
MV1_12A 0                                0
MV1_12B 0                                0
        aff7cf8946e2b926e456f3f95e598cf7 b08946dd4c4340e48f661b0a4029a1c0
MV1_10A 0                                0
MV1_10B 0                                0
MV1_11A 0                                0
MV1_11B 0                                0
MV1_12A 0                                0
MV1_12B 0                                0
        6f5aa87f4b93c070974f8d0cbf63f22c 8011dd36c1c8ecb9262af40146487757
MV1_10A 0                                0
MV1_10B 0                                0
MV1_11A 0                                0
MV1_11B 0                                0
MV1_12A 0                                0
MV1_12B 0                                0
        c456f5262932934ab15e6d5ca6f0ac66 a0ed7ce6c9fd368db9f59b73c259f088
MV1_10A 0                                0
MV1_10B 0                                0
MV1_11A 0                                0
MV1_11B 0                                0
MV1_12A 0                                0
MV1_12B 0                                0
        e1f72b86420b0ab29223b3159e95d3eb afeb62469250fd6d4d40289b29a06c40
MV1_10A 0                                0
MV1_10B 0                                0
MV1_11A 0                                0
MV1_11B 0                                0
MV1_12A 0                                0
MV1_12B 0                                0

[1]   87 2685

                 5e704746baef0d3e632a7def74b449b9
MIRe1_12S_MF_10A     0
MIRe1_12S_MF_10B 42487
MIRe1_12S_MF_11A     0
MIRe1_12S_MF_11B     0
MIRe1_12S_MF_12A     0
MIRe1_12S_MF_12B     0
                 addd57bd3b3937b61b32dece26f8f166
MIRe1_12S_MF_10A 25957
MIRe1_12S_MF_10B     0
MIRe1_12S_MF_11A     0
MIRe1_12S_MF_11B 31805
MIRe1_12S_MF_12A 16427
MIRe1_12S_MF_12B     0
                 918608adb7967723526fc0c0b9026869
MIRe1_12S_MF_10A     0
MIRe1_12S_MF_10B     0
MIRe1_12S_MF_11A     0
MIRe1_12S_MF_11B 13841
MIRe1_12S_MF_12A 12576
MIRe1_12S_MF_12B  1130
                 c75541bd3408a7ac9fb378dd25f9d228
MIRe1_12S_MF_10A 25496
MIRe1_12S_MF_10B  4065
MIRe1_12S_MF_11A  2925
MIRe1_12S_MF_11B 43118
MIRe1_12S_MF_12A  2776
MIRe1_12S_MF_12B     0
                 37c2d350be5db1d723b3d091cfcaa492
MIRe1_12S_MF_10A    0
MIRe1_12S_MF_10B    0
MIRe1_12S_MF_11A    0
MIRe1_12S_MF_11B    0
MIRe1_12S_MF_12A    0
MIRe1_12S_MF_12B 1185
                 6d2fd6c7c4e302d4fd495d55d141a568
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 20f92d11f4596710223e0ea1622b8151
MIRe1_12S_MF_10A     0
MIRe1_12S_MF_10B     0
MIRe1_12S_MF_11A     0
MIRe1_12S_MF_11B 11436
MIRe1_12S_MF_12A     0
MIRe1_12S_MF_12B  4279
                 b788ed4205861dfbe732bceee5d222aa
MIRe1_12S_MF_10A    0
MIRe1_12S_MF_10B 3576
MIRe1_12S_MF_11A    0
MIRe1_12S_MF_11B    0
MIRe1_12S_MF_12A 2254
MIRe1_12S_MF_12B 3668
                 2c4c4cb938987a6880e8975198de429b
MIRe1_12S_MF_10A    0
MIRe1_12S_MF_10B 5515
MIRe1_12S_MF_11A    0
MIRe1_12S_MF_11B    0
MIRe1_12S_MF_12A    0
MIRe1_12S_MF_12B    0
                 a02ef7f5fb571ba596f7846802d3ce4b ⋯
MIRe1_12S_MF_10A    0                             ⋯
MIRe1_12S_MF_10B    0                             ⋯
MIRe1_12S_MF_11A    0                             ⋯
MIRe1_12S_MF_11B 4554                             ⋯
MIRe1_12S_MF_12A  462                             ⋯
MIRe1_12S_MF_12B    0                             ⋯
                 257fbb1e3b68eb28e3e336e5d92ff42d
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 79b6b74d0ad166da5d59209a59e24835
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 ce15bca5d810d710f790fdc1cbc3ccc7
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 bacc275a7008dc82d5ba591cfca4d1ad
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 9db82c74ea2a0234fc5542d6675196ae
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 f4a703890cd020bed7714325620025c7
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 155ca14a2163c210abb09526df5cf797
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 8c554b4b66ccbd21d997258b335bc501
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 6033da90531df3daef6c2cedb7a6cdce
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0
                 cca419ad33609d18d00974fd3bf9b235
MIRe1_12S_MF_10A 0
MIRe1_12S_MF_10B 0
MIRe1_12S_MF_11A 0
MIRe1_12S_MF_11B 0
MIRe1_12S_MF_12A 0
MIRe1_12S_MF_12B 0

[1]  142 4712

In [84]:
write.csv(decontaminated_m3, "/Users/stephanie.rosales/Documents/omics_projects/MIR/Fish_comparison/Working_files/ASV_table_MV3_scrub.csv")

## Identify species that may be missclassified

### Filter taxa SFL and GOM data

In [82]:
gomexSFL= read.csv("/Users/stephanie.rosales/Documents/omics_projects/MIR/taxon_lists/gomex_and_SFLnames.csv",
             header = TRUE) %>%
rename(c("scientificName"="ScientificName_accepted")) %>%
select(scientificName)  #%>%
#mutate_if(is.character, na_if, "")

tail(gomexSFL)
dim(gomexSFL)

obis= read.csv("/Users/stephanie.rosales/Documents/omics_projects/MIR/taxon_lists/gomex_obis_allfish_names.tsv",
             header = TRUE, sep="\t") %>%
select(scientificName)  %>%
mutate_if(is.character, na_if, "")
tail(obis)
dim(obis)

    scientificName
993
994
995
996
997
998

[1] 998   1

     scientificName
1513 Mola mola
1514 Pontinus nematophthalmus
1515 Grammicolepis brachiusculus
1516 Acromycter atlanticus
1517 Symphurus stigmosus
1518 Xenomystax bidentatus

[1] 1518    1

In [83]:
#merge both lists and then remove duplicates
merged_fish_names = full_join(obis, gomexSFL) %>%
distinct(scientificName)
tail(merged_fish_names)
dim(merged_fish_names)

Joining with `by = join_by(scientificName)`

     scientificName
1679 Centrophorus squamosus
1680 Centrophorus tessellatus
1681 Deania calceus
1682 Centroscyllium fabricii
1683 Etmopterus carteri
1684 Etmopterus pusillus

[1] 1684    1

In [29]:
#Find differences between curated (Gomex) and assigned taxa for MARVER1
setdiff(
  unique(as.data.frame(tax_table(taxa_table_1))$Species),
  unique(merged_fish_names$scientificName)
)
length(setdiff(
  unique(as.data.frame(tax_table(taxa_table_1))$Species),
  unique(merged_fish_names$scientificName)
))


# Taxa that are not in curated (Gomex) but in taxa files

taxa_not_in_merged_1 <- as.data.frame(tax_table(taxa_table_1)) %>%
filter(Confidence>=0.99) %>%
  mutate(Species = trimws(tolower(Species))) %>% #Converts all characters to lowercase
  rename(scientificName = Species) %>%
  anti_join(
    merged_fish_names %>%
      mutate(scientificName = trimws(tolower(scientificName))), #Converts all characters to lowercase
    by = "scientificName"
  ) %>%
  filter(Class != "Mammalia",
         Phylum != "Mollusca",
         Genus != "Bos",
         Genus != "Canis",
         Genus != "Gallus",
          Genus != "Homo",
         Genus != "Pan",
         Genus != "Sus",
         Genus!="Meleagris",
         Phylum != "Gallus",
         !is.na(scientificName)) %>%
  arrange(scientificName) %>%
select("Phylum", "Class", "Order","Family","Genus","scientificName")  %>%
filter(Class!="Actinopteri")  %>%
#select("scientificName") %>%
distinct()

taxa_not_in_merged_1

unique(taxa_not_in_merged_1$scientificName)
length(unique(taxa_not_in_merged_1$scientificName))

 [1] NA                            "Homo sapiens"
 [3] "Homo heidelbergensis"        "Hemiramphus far"
 [5] "Gallus gallus"               "Platybelone argala"
 [7] "Sus scrofa"                  "Pan paniscus"
 [9] "Cinachyrella kuekenthali"    "Carangoides bartholomaei"
[11] "Opistognathus jacksoniensis" "Bos primigenius"
[13] "Bos taurus"                  "Pempheris adusta"
[15] "Gobiidae sp."                "Chromis cyanea"
[17] "Canis lupus"                 "Mulloidichthys vanicolensis"
[19] "Brachygenys chrysargyrea"    "Abudefduf sparoides"
[21] "Procyon lotor"               "Oncorhynchus gorbuscha"
[23] "Chelonia mydas"              "Notemigonus crysoleucas"
[25] "Sus cebifrons"               "Xyrias revulsus"
[27] "Bos indicus"                 "Culcita novaeguineae"
[29] "Sparisoma axillare"          "Pterois volitans"
[31] "Pseudogramma paucilepis"     "Cheilopogon doederleinii"
[33] "Antennarius biocellatus"     "Neoniphon aurolineatus"
[35] "Thalassoma jansenii"         "Meleagris gallopavo"
[37] "Rhinesomus triqueter"

[1] 37

                                 Phylum           Class
5cfeed9ca7f9c7ce05701af0ab614f2d p__Chordata_7711 c__Actinopteri_186623
1c58162161dc436d0ca988d73d003c21 p__Chordata_7711 c__Actinopteri_186623
648bc8c5823fb367580f565491247406 p__Chordata_7711 c__class_Testudines_8459
31dbb4e637b8ad9209747c9d80b72bf4 p__Chordata_7711 c__Actinopteri_186623
169a14f60d555bea135059e05910e48f p__Porifera_6040 c__Demospongiae_6042
2d213d2afe422c3e50186542190820af p__Chordata_7711 c__Actinopteri_186623
ed76db8e52546ffe5487e66f1e47ad81 p__Chordata_7711 c__Actinopteri_186623
66cea1d286a7f54fd50dd7bfda152c5a p__Chordata_7711 c__Actinopteri_186623
2a2f2caefb8d83b7a928bb72a1135445 p__Chordata_7711 c__Actinopteri_186623
062c74c86487fa5ccb03c86f11684745 p__Chordata_7711 c__Actinopteri_186623
62e2d9d8db6c62f4281a816a43b33312 p__Chordata_7711 c__Mammalia_40674
ca964911c39cdfd1bdbbe50ff27cabab p__Chordata_7711 c__Actinopteri_186623
c3219ec6317eb5373f33efd2d7b715a8 p__Chordata_7711 c__Actinopteri_186623
f8b81000daddbbaa3242f2fb7c326528 p__Chordata_7711 c__Actinopteri_186623
a9a0ed244c211b9cc5463d292b1c0599 p__Chordata_7711 c__Actinopteri_186623
                                 Order
5cfeed9ca7f9c7ce05701af0ab614f2d o__Lutjaniformes_2024539
1c58162161dc436d0ca988d73d003c21 o__Carangiformes_1489907
648bc8c5823fb367580f565491247406 o__Testudines_8459
31dbb4e637b8ad9209747c9d80b72bf4 o__order_Pomacentridae_30863
169a14f60d555bea135059e05910e48f o__Tetractinellida_1779164
2d213d2afe422c3e50186542190820af o__Gobiiformes_1489878
ed76db8e52546ffe5487e66f1e47ad81 o__Holocentriformes_1490028
66cea1d286a7f54fd50dd7bfda152c5a o__Cypriniformes_7952
2a2f2caefb8d83b7a928bb72a1135445 o__Acropomatiformes_3051910
062c74c86487fa5ccb03c86f11684745 o__Beloniformes_76071
62e2d9d8db6c62f4281a816a43b33312 o__Carnivora_33554
ca964911c39cdfd1bdbbe50ff27cabab o__Perciformes_8111
c3219ec6317eb5373f33efd2d7b715a8 o__Perciformes_8111
f8b81000daddbbaa3242f2fb7c326528 o__Tetraodontiformes_31022
a9a0ed244c211b9cc5463d292b1c0599 o__Anguilliformes_7933
                                 Family              Genus
5cfeed9ca7f9c7ce05701af0ab614f2d c__Actinopteri      Brachygenys
1c58162161dc436d0ca988d73d003c21 c__Actinopteri      Carangoides
648bc8c5823fb367580f565491247406 c__class_Testudines Chelonia
31dbb4e637b8ad9209747c9d80b72bf4 c__Actinopteri      Chromis
169a14f60d555bea135059e05910e48f c__Demospongiae     Cinachyrella
2d213d2afe422c3e50186542190820af c__Actinopteri      genus_Gobiidae sp.
ed76db8e52546ffe5487e66f1e47ad81 c__Actinopteri      Neoniphon
66cea1d286a7f54fd50dd7bfda152c5a c__Actinopteri      Notemigonus
2a2f2caefb8d83b7a928bb72a1135445 c__Actinopteri      Pempheris
062c74c86487fa5ccb03c86f11684745 c__Actinopteri      Platybelone
62e2d9d8db6c62f4281a816a43b33312 c__Mammalia         Procyon
ca964911c39cdfd1bdbbe50ff27cabab c__Actinopteri      Pseudogramma
c3219ec6317eb5373f33efd2d7b715a8 c__Actinopteri      Pterois
f8b81000daddbbaa3242f2fb7c326528 c__Actinopteri      Rhinesomus
a9a0ed244c211b9cc5463d292b1c0599 c__Actinopteri      Xyrias
                                 scientificName
5cfeed9ca7f9c7ce05701af0ab614f2d brachygenys chrysargyrea
1c58162161dc436d0ca988d73d003c21 carangoides bartholomaei
648bc8c5823fb367580f565491247406 chelonia mydas
31dbb4e637b8ad9209747c9d80b72bf4 chromis cyanea
169a14f60d555bea135059e05910e48f cinachyrella kuekenthali
2d213d2afe422c3e50186542190820af gobiidae sp.
ed76db8e52546ffe5487e66f1e47ad81 neoniphon aurolineatus
66cea1d286a7f54fd50dd7bfda152c5a notemigonus crysoleucas
2a2f2caefb8d83b7a928bb72a1135445 pempheris adusta
062c74c86487fa5ccb03c86f11684745 platybelone argala
62e2d9d8db6c62f4281a816a43b33312 procyon lotor
ca964911c39cdfd1bdbbe50ff27cabab pseudogramma paucilepis
c3219ec6317eb5373f33efd2d7b715a8 pterois volitans
f8b81000daddbbaa3242f2fb7c326528 rhinesomus triqueter
a9a0ed244c211b9cc5463d292b1c0599 xyrias revulsus

 [1] "brachygenys chrysargyrea" "carangoides bartholomaei"
 [3] "chelonia mydas"           "chromis cyanea"
 [5] "cinachyrella kuekenthali" "gobiidae sp."
 [7] "neoniphon aurolineatus"   "notemigonus crysoleucas"
 [9] "pempheris adusta"         "platybelone argala"
[11] "procyon lotor"            "pseudogramma paucilepis"
[13] "pterois volitans"         "rhinesomus triqueter"
[15] "xyrias revulsus"

[1] 15

| Taxon                    | Common Name        | Primary Region / Distribution | Plausible in Caribbean eDNA? | Notes                             |
| ------------------------ | ------------------ | ----------------------------- | ---------------------------- | --------------------------------- |
| Carangoides bartholomaei | Yellow jack        | Western Atlantic / Caribbean  | Yes                          | Common pelagic reef fish          |
| Chelonia mydas           | Green sea turtle   | Global tropical oceans        | Yes                          | Common in Florida waters          |
| Chromis cyanea           | Blue chromis       | Caribbean                     | Yes                          | Common reef fish                  |
| Neoniphon aurolineatus   | Squirrelfish       | Western Atlantic              | Yes                          | Caribbean reef fish               |
| Pseudogramma paucilepis  | Reef basslet       | Western Atlantic              | Yes                          | Caribbean reef species            |
| Pterois volitans         | Lionfish           | Indo-Pacific (invasive)       | Yes                          | Established invasive in Caribbean |
| Rhinesomus triqueter     | Reef squirrelfish  | Caribbean                     | Yes                          | Reef fish                         |
| Procyon lotor            | Raccoon            | North America                 | Yes                          | Likely terrestrial runoff DNA     |
| Gobiidae                 | Gobies             | Global                        | Yes                          | Family-level ID                   |
| Cinachyrella kuekenthali | Marine sponge      | Indo-Pacific mostly           | Possibly                     | Sponge taxonomy uncertain         |
| Platybelone argalus      | Needlefish         | Tropical oceans               | Possibly                     | Widespread genus                  |
| Brachygenys chrysargyrea | Uncertain taxonomy | Unclear                       | Uncertain                    | Taxonomic ambiguity               |
| Pempheris adusta         | Sweeper fish       | Indo-Pacific                  | No                           | Likely taxonomic misassignment    |
| Notemigonus crysoleucas  | Freshwater fish    | North America freshwater      | No                           | Freshwater species                |
| Xyrias revulsus          | Snake eel          | Indo-Pacific                  | No                           | Regional mismatch                 |

Pempheris adusta = no regional similarties; 
could be
Xyrias revulsus = Ophisurus macrorhynchos

In [30]:
#Find differences between curated (Gomex) and assigned taxa for MARVER3
setdiff(
  unique(as.data.frame(tax_table(taxa_table_3))$Species),
  unique(merged_fish_names$scientificName)
)
length(setdiff(
  unique(as.data.frame(tax_table(taxa_table_3))$Species),
  unique(merged_fish_names$scientificName)
))


# Taxa that are not in curated (Gomex) but in taxa files

taxa_not_in_merged_3 <- as.data.frame(tax_table(taxa_table_3)) %>%
  mutate(Species = trimws(tolower(Species))) %>% #Converts all characters to lowercase
  rename(scientificName = Species) %>%
  anti_join(
    merged_fish_names %>%
      mutate(scientificName = trimws(tolower(scientificName))), #Converts all characters to lowercase
    by = "scientificName"
  ) %>%
  filter(Class != "Mammalia",
         Phylum != "Mollusca",
         Genus != "Bos",
         Genus != "Canis",
         Genus != "Gallus",
          Genus != "Homo",
         Genus != "Pan",
         Genus != "Sus",
         Genus!="Meleagris",
         Phylum != "Gallus",
         !is.na(scientificName)) %>%
  arrange(scientificName) %>%
select("Phylum", "Class", "Order","Family","Genus","scientificName")  %>%
filter(Class!="Actinopteri")  %>%
#select("scientificName") %>%
distinct()

taxa_not_in_merged_3

unique(taxa_not_in_merged_3$scientificName)
length(unique(taxa_not_in_merged_3$scientificName))

 [1] NA                             "Homo sapiens"
 [3] "Spondylus ambiguus"           "NA"
 [5] "Coryphopterus urospilus"      "Carangoides bartholomaei"
 [7] "Sphyraena jello"              "Ophichthus erabo"
 [9] "Cyclothone atraria"           "Tigrigobius gemmatus"
[11] "Aglaura hemistoma"            "Trachinotus falcatus"
[13] "Dysidea avara"                "Platybelone argala"
[15] "Echeneis naucratoides"        "Eucinostomus currani"
[17] "Gillellus semicinctus"        "Carangoides ruber"
[19] "Lythrypnus sp. AC-2023"       "Gallus gallus"
[21] "Ogilbichthys sp. USNM 349073" "Canis lupus"
[23] "Platanista minor"             "Myrichthys maculosus"
[25] "Bos taurus"                   "Neoniphon opercularis"
[27] "Sargocentron punctatissimum"  "Alloclinus holderi"

[1] 28

                                 Phylum   Class        Order
1797e67d1bf2cbd03e3f3b67184f7b16 Cnidaria Hydrozoa     Trachymedusae
2094f16b49540a52de156e3c11ef1dab Porifera Demospongiae Dictyoceratida
05dbcf4106fa6e047c3d2468cb29b278 NA       NA           NA
0ed2a119534e3e3a7bd3bb237f0b032c Cnidaria Anthozoa     Scleractinia
367d5d6ab8c51c02032c7f618f665210 Porifera Demospongiae Haplosclerida
8fd9ec1b22d5c38a48976482d8559b9e Chordata NA           NA
                                 Family           Genus
1797e67d1bf2cbd03e3f3b67184f7b16 Rhopalonematidae Aglaura
2094f16b49540a52de156e3c11ef1dab Dysideidae       Dysidea
05dbcf4106fa6e047c3d2468cb29b278 NA               NA
0ed2a119534e3e3a7bd3bb237f0b032c NA               NA
367d5d6ab8c51c02032c7f618f665210 Callyspongiidae  Callyspongia
8fd9ec1b22d5c38a48976482d8559b9e NA               NA
                                 scientificName
1797e67d1bf2cbd03e3f3b67184f7b16 aglaura hemistoma
2094f16b49540a52de156e3c11ef1dab dysidea avara
05dbcf4106fa6e047c3d2468cb29b278 na
0ed2a119534e3e3a7bd3bb237f0b032c na
367d5d6ab8c51c02032c7f618f665210 na
8fd9ec1b22d5c38a48976482d8559b9e na

[1] "aglaura hemistoma" "dysidea avara"     "na"

[1] 3